
service: mrt-traffic-function

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

  stage: prod
  region: ap-northeast-1

# you can add statements to the Lambda function's IAM Role here
  iam:
    role: arn:aws:iam::250172214346:role/lambda-s3-role
  environment:
    company: tpe_mrt
    s3_target_bucket: s3://online-data-lake-thirty-three/mrt-traffic
    target_db: open_data
    target_tbl: tpe_mrt_traffic
    write_data_operation: append
  layers:
    - arn:aws:lambda:ap-northeast-1:770693421928:layer:Klayers-p39-requests:13
    - arn:aws:lambda:ap-northeast-1:336392948345:layer:AWSSDKPandas-Python39:6

functions:
  mrt_traffic:
    handler: handler.mrt_traffic
    timeout: 180
    memorySize: 2048

  mrt_traffic_file_list:
    handler: handler.mrt_traffic_file_list
    timeout: 180
    memorySize: 128

  email_notification:
    handler: handler.email_notification
    timeout: 180
    memorySize: 128 

